import { Registry } from "./registry";
import type { PropDef, TrapDef } from "./types";
import { Surface } from "./types";

/** Physical props. Every dynamic prop is a real rigid body: it tumbles,
 * blocks, can be thrown with Grasp, and breaks into whatever it held. */
export const PROPS = new Registry<PropDef>("prop");

PROPS.register(
  { id: "crate", name: "Crate", shape: { kind: "box", half: [0.38, 0.38, 0.38] }, mass: 22, material: "wood", hp: 20, flammable: true, lootChance: 0.18, grabbable: true, model: "crate" },
  { id: "crate_small", name: "Small Crate", shape: { kind: "box", half: [0.26, 0.26, 0.26] }, mass: 9, material: "wood", hp: 10, flammable: true, lootChance: 0.12, grabbable: true, model: "crate_small" },
  { id: "barrel", name: "Barrel", shape: { kind: "cylinder", radius: 0.34, halfHeight: 0.45 }, mass: 35, material: "wood", hp: 26, flammable: true, lootChance: 0.12, grabbable: true, model: "barrel" },
  {
    id: "oil_barrel",
    name: "Lamp-oil Barrel",
    shape: { kind: "cylinder", radius: 0.34, halfHeight: 0.45 },
    mass: 40,
    material: "wood",
    hp: 14,
    flammable: true,
    grabbable: true,
    onBreak: [{ type: "surface", surface: Surface.Oil, radius: 2.6 }],
    model: "barrel_oil",
  },
  {
    id: "powder_keg",
    name: "Powder Keg",
    shape: { kind: "cylinder", radius: 0.28, halfHeight: 0.36 },
    mass: 25,
    material: "wood",
    hp: 8,
    flammable: true,
    grabbable: true,
    onBreak: [
      { type: "explode", radius: 4.2, damage: 45, element: "fire", impulse: 38 },
      { type: "surface", surface: Surface.Fire, radius: 1.8 },
      { type: "noise", loudness: 30 },
    ],
    model: "keg_powder",
  },
  { id: "urn", name: "Funerary Urn", shape: { kind: "cylinder", radius: 0.24, halfHeight: 0.34 }, mass: 8, material: "ceramic", hp: 4, lootChance: 0.22, grabbable: true, onBreak: [{ type: "fx", fx: "ash_puff" }], model: "urn" },
  { id: "bone_pile", name: "Bone Pile", shape: { kind: "box", half: [0.4, 0.18, 0.4] }, mass: 15, material: "bone", hp: 6, lootChance: 0.08, grabbable: false, model: "bone_pile" },
  {
    id: "candelabrum",
    name: "Candelabrum",
    shape: { kind: "cylinder", radius: 0.2, halfHeight: 0.7 },
    mass: 18,
    material: "metal",
    grabbable: true,
    light: { color: "#ffb35a", intensity: 2.2, radius: 7, flicker: 0.6 },
    fx: "candle_flames",
    model: "candelabrum",
  },
  {
    id: "oil_lamp",
    name: "Hanging Oil Lamp",
    shape: { kind: "cylinder", radius: 0.14, halfHeight: 0.2 },
    mass: 4,
    material: "glass",
    hp: 3,
    grabbable: true,
    light: { color: "#ffa04a", intensity: 2.6, radius: 8, flicker: 0.4 },
    onBreak: [
      { type: "surface", surface: Surface.Oil, radius: 1.3 },
      { type: "surface", surface: Surface.Fire, radius: 0.9 },
    ],
    model: "oil_lamp",
  },
  { id: "coffin", name: "Coffin", shape: { kind: "box", half: [0.35, 0.3, 0.95] }, mass: 70, material: "wood", hp: 30, flammable: true, lootChance: 0.35, grabbable: false, model: "coffin" },
  { id: "sarcophagus", name: "Sarcophagus", shape: { kind: "box", half: [0.5, 0.45, 1.1] }, mass: 0, material: "stone", model: "sarcophagus" },
);

/** Traps. Triggers are physical: plates count resting mass, so a crate,
 * a corpse or a fat rat will set them off as readily as you. */
export const TRAPS = new Registry<TrapDef>("trap");

TRAPS.register(
  {
    id: "spike_plate",
    name: "Spike Plate",
    desc: "A slab that sinks a finger's width, then spears.",
    trigger: "plate",
    minMass: 6,
    radius: 0.7,
    rearm: 2.5,
    delay: 0.25,
    action: "spikes",
    damage: 26,
    element: "physical",
    effects: [{ type: "status", status: "bleeding", duration: 4 }],
    visibility: 0.35,
    mount: "floor",
    model: "trap_spikes",
  },
  {
    id: "dart_wall",
    name: "Dart Slot",
    desc: "A mouth in the wall that spits when something crosses its line.",
    trigger: "sight",
    radius: 12,
    rearm: 1.6,
    delay: 0.1,
    action: "darts",
    damage: 10,
    element: "physical",
    visibility: 0.5,
    mount: "wall",
    model: "trap_dart",
  },
  {
    id: "flame_vent",
    name: "Flame Vent",
    desc: "A grate that breathes fire on a pressure plate's word.",
    trigger: "plate",
    minMass: 6,
    radius: 0.7,
    rearm: 4,
    delay: 0.35,
    action: "flame",
    damage: 14,
    element: "fire",
    effects: [{ type: "surface", surface: Surface.Fire, radius: 1.2 }],
    visibility: 0.6,
    mount: "floor",
    model: "trap_flame",
  },
  {
    id: "collapse_floor",
    name: "Rotten Floor",
    desc: "Boards over a drop. They hold a rat. They don't hold you.",
    trigger: "plate",
    minMass: 30,
    radius: 1.2,
    rearm: 0,
    delay: 0.5,
    action: "collapse",
    damage: 0,
    element: "physical",
    visibility: 0.25,
    mount: "floor",
    model: "trap_collapse",
  },
);
