import { Registry } from "./registry";
import type { StatusDef } from "./types";

/** Status effects — the per-body half of the emergence engine (surfaces are
 * the per-floor half). The sim applies them uniformly to delvers, creatures
 * and anything else with health. */
export const STATUSES = new Registry<StatusDef>("status");

STATUSES.register(
  {
    id: "burning",
    name: "Burning",
    desc: "On fire. Spreads to oil, webs, spores and flammable neighbours. Water puts it out.",
    duration: 4,
    dps: 6,
    element: "fire",
    removes: ["chilled", "frozen", "webbed"],
    color: "#ff7a2a",
  },
  {
    id: "wet",
    name: "Wet",
    desc: "Soaked. Can't burn; lightning hurts more; frost freezes solid.",
    duration: 6,
    removes: ["burning", "oiled"],
    combos: [{ when: "chilled", into: "frozen" }],
    damageTakenMult: 1,
    color: "#5aa9ff",
  },
  {
    id: "chilled",
    name: "Chilled",
    desc: "Slowed by cold. Wet and chilled together freeze solid.",
    duration: 4,
    moveMult: 0.6,
    element: "frost",
    removes: ["burning"],
    combos: [{ when: "wet", into: "frozen" }],
    color: "#a8e6ff",
  },
  {
    id: "frozen",
    name: "Frozen",
    desc: "Encased in ice. Cannot move or act; shatters for bonus damage from force.",
    duration: 2.5,
    moveMult: 0,
    incapacitates: true,
    damageTakenMult: 1.25,
    removes: ["burning", "wet", "chilled"],
    color: "#d8f6ff",
  },
  {
    id: "shocked",
    name: "Shocked",
    desc: "Jolted. Twitching limbs, interrupted casts.",
    duration: 1.2,
    moveMult: 0.7,
    element: "storm",
    color: "#e8f07a",
  },
  {
    id: "poisoned",
    name: "Poisoned",
    desc: "Venom in the blood.",
    duration: 6,
    dps: 3,
    element: "venom",
    color: "#7fe05a",
  },
  {
    id: "oiled",
    name: "Oiled",
    desc: "Slick with oil. The next spark sets you alight.",
    duration: 10,
    moveMult: 0.95,
    color: "#3a2f24",
  },
  {
    id: "stunned",
    name: "Stunned",
    desc: "Senseless for a moment.",
    duration: 1,
    moveMult: 0,
    incapacitates: true,
    color: "#ffffff",
  },
  {
    id: "slowed",
    name: "Slowed",
    desc: "Honey, tar, mud — every step is work.",
    duration: 2,
    moveMult: 0.5,
    color: "#d9a13a",
  },
  {
    id: "webbed",
    name: "Webbed",
    desc: "Caught in web. Fire frees you (painfully).",
    duration: 2.5,
    moveMult: 0.15,
    color: "#e8e6dc",
  },
  {
    id: "bleeding",
    name: "Bleeding",
    desc: "Leaving a trail — and scent.",
    duration: 5,
    dps: 2,
    element: "physical",
    color: "#b3122a",
  },
  {
    id: "feared",
    name: "Feared",
    desc: "Runs from the source of terror, heedless of traps.",
    duration: 3,
    moveMult: 1.15,
    color: "#8a5cff",
  },
  {
    id: "blessed",
    name: "Blessed",
    desc: "A mercy candle's warmth: regeneration.",
    duration: 8,
    dps: -4,
    color: "#ffe9a8",
  },
  {
    id: "invisible",
    name: "Unseen",
    desc: "Creatures can't see you until you strike.",
    duration: 6,
    color: "#9aa0b8",
  },
  {
    id: "blinded",
    name: "Blinded",
    desc: "Ink, steam or a snuffed candle: sight shrinks to a few metres.",
    duration: 3,
    color: "#2a2438",
  },
  {
    id: "silenced",
    name: "Silenced",
    desc: "Shushed. No spell will come.",
    duration: 1.5,
    color: "#c8c0e8",
  },
);
