import type { SurfaceDef } from "./types";
import { Surface } from "./types";

/** Floor surfaces — the per-floor half of the emergence engine. A floor
 * keeps a 0.5 m grid of these (sim/surfaces.ts); elements react with them
 * (`reactions`), fire spreads through `flammable` ones, and bodies standing
 * in them get `applies` and `dps`. */
const defs: SurfaceDef[] = [
  { kind: Surface.None, id: "none", name: "Ground", friction: 1, moveMult: 1, lifetime: 0, color: "#000000", roughness: 1 },
  {
    kind: Surface.Water,
    id: "water",
    name: "Water",
    friction: 0.8,
    moveMult: 0.85,
    applies: "wet",
    lifetime: 0,
    reactions: { frost: Surface.Ice, fire: Surface.None, storm: Surface.Water },
    color: "#1c2a33",
    roughness: 0.05,
    liquid: true,
  },
  {
    kind: Surface.Oil,
    id: "oil",
    name: "Oil",
    friction: 0.35,
    moveMult: 0.9,
    applies: "oiled",
    lifetime: 0,
    reactions: { fire: Surface.Fire },
    flammable: true,
    color: "#17120c",
    roughness: 0.08,
    liquid: true,
  },
  {
    kind: Surface.Blood,
    id: "blood",
    name: "Blood",
    friction: 0.7,
    moveMult: 1,
    lifetime: 90,
    reactions: { frost: Surface.Ice },
    color: "#3a0508",
    roughness: 0.2,
  },
  {
    kind: Surface.Ice,
    id: "ice",
    name: "Ice",
    friction: 0.04,
    moveMult: 1,
    lifetime: 30,
    reactions: { fire: Surface.Water },
    color: "#b8e4f2",
    roughness: 0.04,
  },
  {
    kind: Surface.Fire,
    id: "fire",
    name: "Fire",
    friction: 1,
    moveMult: 1,
    applies: "burning",
    dps: 8,
    dpsElement: "fire",
    lifetime: 7,
    reactions: { frost: Surface.Water },
    color: "#ff6a1a",
    roughness: 0.9,
    emissive: 3,
  },
  {
    kind: Surface.Web,
    id: "web",
    name: "Web",
    friction: 1,
    moveMult: 0.3,
    applies: "webbed",
    lifetime: 0,
    reactions: { fire: Surface.Fire },
    flammable: true,
    color: "#e8e6dc",
    roughness: 0.9,
  },
  {
    kind: Surface.Acid,
    id: "acid",
    name: "Acid",
    friction: 0.9,
    moveMult: 0.85,
    dps: 10,
    dpsElement: "venom",
    lifetime: 20,
    color: "#6cff3a",
    roughness: 0.15,
    emissive: 0.6,
    liquid: true,
  },
  {
    kind: Surface.Spores,
    id: "spores",
    name: "Spores",
    friction: 1,
    moveMult: 1,
    applies: "poisoned",
    lifetime: 12,
    reactions: { fire: Surface.Fire },
    flammable: true,
    color: "#c7d96a",
    roughness: 0.9,
    emissive: 0.3,
  },
  {
    kind: Surface.Honey,
    id: "honey",
    name: "Honey",
    friction: 1.5,
    moveMult: 0.4,
    applies: "slowed",
    lifetime: 0,
    reactions: { fire: Surface.Fire },
    flammable: true,
    color: "#d98f1a",
    roughness: 0.1,
    liquid: true,
  },
  { kind: Surface.Ash, id: "ash", name: "Ash", friction: 0.9, moveMult: 1, lifetime: 60, color: "#3a3634", roughness: 1 },
  {
    kind: Surface.Slime,
    id: "slime",
    name: "Slime",
    friction: 0.25,
    moveMult: 0.8,
    applies: "slowed",
    lifetime: 40,
    color: "#5f8a3a",
    roughness: 0.12,
  },
  {
    kind: Surface.Ink,
    id: "ink",
    name: "Ink",
    friction: 0.6,
    moveMult: 0.9,
    lifetime: 0,
    reactions: { fire: Surface.Fire },
    flammable: true,
    color: "#07060d",
    roughness: 0.06,
    liquid: true,
  },
  {
    kind: Surface.Lava,
    id: "lava",
    name: "Lava",
    friction: 1,
    moveMult: 0.5,
    applies: "burning",
    dps: 45,
    dpsElement: "fire",
    lifetime: 0,
    color: "#ff4a0a",
    roughness: 0.6,
    emissive: 5,
    liquid: true,
  },
];

export const SURFACES: readonly SurfaceDef[] = defs;

export function surfaceDef(kind: Surface): SurfaceDef {
  return defs[kind] ?? defs[0];
}
