import type { NpcText } from "./types";

/** Village NPC barks. Lines ≤ 140 chars. `depthLines` are keyed by the
 * delver's deepest floor reached; show a line from the highest entry whose
 * minFloor ≤ deepest. */
export const NPCS: Record<string, NpcText> = {
  mother_sallow: {
    name: "Mother Sallow",
    title: "Apothecary — The Sallow Jar",
    shop: "apothecary",
    greeting: [
      "Sit. Open your mouth. No, I'm not asking, I'm looking.",
      "The Sallow Jar. If it's bitter, it's working.",
      "You look like a person who's been sleeping in the wrong place.",
      "Salves on the left, draughts on the right, opinions free.",
      "Back again. Good. The Well hasn't had you yet.",
    ],
    idle: [
      "I've a brick in the oven for Orrin's side of the bed. Forty years. It's a good brick.",
      "Lumen cap for the eyes, ichor for the holes, nothing at all for the heart. Don't ask.",
      "Chew the root, don't swallow it. Nobody listens. That's why I'm rich.",
      "People say I'm bitter. I'm an apothecary. Bitter's the job.",
      "If you hear the bell ring at night, you close your window and mind your business.",
      "Things come up on the breath. Jars, mostly. Some I can't open. Some I shouldn't.",
      "Drink it all. The bottom's the best bit. That's true of more than draughts.",
    ],
    onReturn: [
      "There you are. Tongue out. Hm. Plenty of dream in your teeth. Drink this.",
      "Bread and salt at the Stump, then bed. I'll not ask you a thing. I'll want to.",
      "Came back heavier than you went. Good. Gold weighs better than grief.",
      "You smell of candle smoke and something else. Wash before you hug anybody.",
      "Home. Sit. The floor's not moving, it only feels like it.",
    ],
    onDeath: [
      "Your candle guttered. The Chandler came and told me. I told the brick.",
      "The dream kept your things. It keeps everything. Don't let it keep your nerve.",
      "Died, did you? Well, you're here now, and cold. Tea.",
      "Orrin died down there once, came back up, then went down again anyway. Don't be Orrin.",
      "Lost the lot? The Well's a thief with good manners. It leaves you a Reliquary to cry on.",
    ],
    depthLines: [
      { minFloor: 5, lines: ["Five breaths deep and back. You'll do. Most don't, first time."] },
      { minFloor: 10, lines: ["Past the Sexton? He was a Crane, you know. Don't tell the Cranes."] },
      { minFloor: 20, lines: ["The Archive. Did the water taste of anything? No. Good. Don't tell me if it did."] },
      { minFloor: 30, lines: ["You've been in the Choir. You're humming. Stop humming."] },
      { minFloor: 40, lines: ["Forty. Orrin got to forty-one. Then the Well took him. Or he took it, he'd say."] },
      { minFloor: 60, lines: ["Sixty? Nobody's grandmother was ever sixty deep. Sit down before you tell me anything."] },
      { minFloor: 80, lines: ["You smell of brass and dark. I'll not ask. It's not morning."] },
      { minFloor: 100, lines: ["You've seen it, haven't you. Its face. Don't. Don't tell me. Tell me."] },
    ],
    secretHints: [
      "The bell hasn't a tongue, but lightning's a tongue of a sort. So they say. So I've heard.",
      "Absalom writes down what his well says at night. The night bits are the interesting bits.",
      "There's a jar under my counter with no label. Ask me about it when you've been properly deep.",
      "My mother said the Giant's warm at night if you stand on his thumb. My mother said a lot.",
    ],
  },

  brannoc: {
    name: "Brannoc Two-Thumbs",
    title: "Artificer — The Cinder Bench",
    shop: "artificer",
    greeting: [
      "Cinder Bench. Mind the bench, it's hot. Mind the other bench, it's hotter.",
      "Two thumbs, one opinion: that's good kit and you've been hitting things with it.",
      "Put it on the anvil. Gently. It remembers being made, and it'll remember you.",
      "What'll it be — better, different, or on fire?",
    ],
    idle: [
      "I don't believe in God. I believe in tolerances. God's just a very loose one.",
      "Grave tallow binds it, slag iron hardens it, and a kind word helps more than you'd think.",
      "Twice as handy, half as welcome at weddings. Nobody wants two thumbs near the cake.",
      "Everything's made twice. Once in your head, once in the fire. The second one always sulks.",
      "An upgrade's a mark on a bone. Don't ask me why. It works, and it's quieter than asking.",
      "That? Not for sale. That's a... paperweight. Don't touch it.",
      "If a thing breaks, it's the maker's fault. If it breaks twice, it's the maker's fault twice.",
    ],
    onReturn: [
      "Let's see the damage. Mm. You've been using the sharp end. Good.",
      "Brought me something from down there? In the bucket. Not that bucket.",
      "Came back with all your fingers? Count them. I always count mine. Eleven. Still eleven.",
      "That staff's got soot in its joints. It's been somewhere hot. It likes you.",
    ],
    onDeath: [
      "Your kit's in a Reliquary down there. A coffer's holding it. Things are patient.",
      "Died, eh? Still got your hands? Then you can still hold a hammer. Start there.",
      "The dream keeps what it touches. So do I. Give it here, I'll make you something new.",
      "It's not the dying. It's walking back past the bench with nothing on. That's what stings.",
    ],
    depthLines: [
      { minFloor: 10, lines: ["Undercroft bone. Lovely grain. Bowe knew how to keep a thing."] },
      { minFloor: 30, lines: ["Choir spore. Makes two things agree. Wish I had some for my brothers."] },
      { minFloor: 34, lines: ["Foundry heat on your eyebrows. That's where I went. Thirty-eight. Once was plenty."] },
      { minFloor: 40, lines: ["Past the Last Attempt. Were its hands... were they empty? Right. Right. Thanks."] },
      { minFloor: 70, lines: ["Orrery gear. Look at that cut. Nobody alive can cut like that. Nobody dead, mostly."] },
      { minFloor: 90, lines: ["Umbral glass. I'll set it, but I won't grind it. It looks back."] },
      { minFloor: 100, lines: ["You went to the bottom and came back. I'd like to shake your hand. With both of mine."] },
    ],
    secretHints: [
      "The Chandlery's got a drawing of the Giant from before my granddad. The hand looks different. Just saying.",
      "Waking Bells need a filing off the old bell's lip. That's all I'll say. That's more than I should.",
      "Force'll shift rubble. The rubble behind the Giant's knee, for instance. For instance.",
      "That brass figure? Found it on thirty-eight in an apron pocket. No, I won't say whose.",
    ],
  },

  mistress_vey: {
    name: "Mistress Vey",
    title: "Wagers — The Hollow Coin",
    shop: "wagers",
    greeting: [
      "The Hollow Coin. Everything's a bet, darling. I just write them down.",
      "Sit. Pick a veil. One of them's lovely. Two of them are lessons.",
      "Your odds went up this morning. Don't let it go to your head. They come down too.",
      "Ah. My favourite long shot.",
    ],
    idle: [
      "Eleven faces on a die of the Well. Ten for the strata, one for the house.",
      "I don't cheat. The Well cheats. I simply keep better records than the Well.",
      "Everybody here's a gambler. Some of us have the decency to charge for it.",
      "I've odds on every delver in Kneel. I'll show you yours for double. People always pay double.",
      "Certainty is terrible for business. I like the world exactly as uncertain as it is.",
      "Veiled things are only frightening until you pay. Then they're only disappointing.",
      "The Order bets too. They call it faith and never settle up.",
    ],
    onReturn: [
      "You came back. I had you at four to one. I'm a little annoyed and very pleased.",
      "Alive and loaded. Care to double it? No? Wise. Boring, but wise.",
      "Someone lost money on you tonight, darling. It wasn't me.",
      "Back up the Well. The house congratulates you and would like a small percentage.",
    ],
    onDeath: [
      "Oh dear. I had you at evens. The Well had you, and I had you, so we're both even.",
      "Everyone who died had odds. Yours were quite respectable, if that helps.",
      "Your Reliquary's down there gathering interest. That's a joke. It gathers dust.",
      "Death's just a long losing streak with a clean ending. Pick a veil. Cheer up.",
    ],
    depthLines: [
      { minFloor: 5, lines: ["Five floors. I've moved you from 'unlikely' to 'merely foolish'."] },
      { minFloor: 20, lines: ["Twenty. You're shorter odds than the weather now. Congratulations."] },
      { minFloor: 40, lines: ["Forty. Nobody bets against you now. It's very dull. Do something reckless."] },
      { minFloor: 60, lines: ["Sixty. I've stopped taking bets on you. Nobody will lay against."] },
      { minFloor: 90, lines: ["Ninety. You've a column of your own. It hasn't a heading. I didn't know what to write."] },
      { minFloor: 100, lines: ["The bottom. I owe the house a great deal of money. Worth it, darling."] },
    ],
    secretHints: [
      "The Order had two rules on the lintel once. I'd give good odds on what the second one said.",
      "Pell's pincushion has a face. Pell says it's a guess. I'd take that bet if I knew how to settle it.",
      "The Stump's empty chair is a sucker bet. Sit by it after you've died a few times and see who pays.",
    ],
  },

  pell: {
    name: "Pell",
    title: "Tailor — Pell & Needle",
    shop: "tailor",
    greeting: [
      "Pell and Needle. Arms out, please. Both. Thank you. Other way.",
      "Mm. Hello. Stand on the box. I'll measure for two things at once. Saves a trip.",
      "You've torn your hem on something with teeth. Don't tell me what. I'll guess.",
      "Colours, cuts, trims. All of it silly. All of it matters.",
    ],
    idle: [
      "A robe and a shroud are the same garment, really. One of them has better pockets.",
      "Grey goes with everything. Especially the fog.",
      "The pincushion? It's the Giant's head. As I imagine it. Nobody's seen it. I guessed.",
      "I don't talk loudly. Things in the fog listen, and they've awful taste.",
      "Red thread at the wrist is very fashionable this year. With certain people. Ask no one.",
      "Your lantern colour says a lot about you. Yours says, 'please don't eat me'.",
      "Stitches are just very small promises. I keep all of mine.",
    ],
    onReturn: [
      "You're back. Your hood's back. Most of your hood's back.",
      "Stand still. You've dream on your collar. There. Gone. Don't ask what it was.",
      "Everything fits better after a good fright. It's the posture.",
      "You came home in one piece. That's the only fit that matters. Well. Almost.",
    ],
    onDeath: [
      "I had your shroud half-finished. I'll put it back in the drawer. Plenty of time. I hope.",
      "Your robe's in a coffer somewhere down there. I'll make you another. Better seams.",
      "Oh. Oh, dear. Stand up straight. You're not dead now. There. Better.",
      "The Well always takes the good cloth. Never the socks. It has no interest in socks.",
    ],
    depthLines: [
      { minFloor: 10, lines: ["Bone dust in the weave. The Undercroft. It'll brush out. Mostly."] },
      { minFloor: 20, lines: ["Waterlogged. The Archive's hard on linen. Hard on everything."] },
      { minFloor: 50, lines: ["You smell of honey and your seams are sticky. I'll charge extra. I'll enjoy it."] },
      { minFloor: 60, lines: ["Frost in the fibres, and it doesn't melt. How strange. How lovely."] },
      { minFloor: 80, lines: ["You've been somewhere dark and come back a shade darker. Suits you, honestly."] },
      { minFloor: 100, lines: ["Did you see its face? Tell me one thing. The nose. Did I get the nose right?"] },
    ],
    secretHints: [
      "When you've been all the way down, come and look at my pincushion. I'd like a second opinion.",
      "Carry a pocket stone from someone else's Reliquary to the Rope Walk. I've a grey that suits it.",
      "The Chandler's grey and the Wakers' red. I sell to both. I sell to everyone. It's called trade.",
    ],
  },

  old_hask: {
    name: "Old Hask",
    title: "Quartermaster — The Lending House",
    shop: "quartermaster",
    greeting: [
      "Lending House. You borrow, you bring back, or it brings itself back. One way or another.",
      "What depth are we pretending you are today?",
      "Sign here. Other here. Here's where you swear. Don't swear at me, swear in the book.",
      "Kit's weighed, candle's lit, buckles are sound. Mind the third buckle. It knows things.",
    ],
    idle: [
      "Light gear. The Well takes you as deep as you are heavy, so I lend you a lighter you.",
      "Every kit's got a candle in the back room. Candle goes out, kit comes home. Folded. Damp.",
      "One eye's enough for buckles. The other one I lent out. Joke. Mostly.",
      "I've done this since before your gran borrowed her first hood. She brought it back late.",
      "Don't sell it, don't stash it, don't drop it. It isn't yours. That's what makes it light.",
      "The ledger goes back further than me. Somebody's got to keep it. I keep it.",
      "Bring back what's mine. Keep what you find. Fair's fair; the Well's the one that isn't.",
    ],
    onReturn: [
      "Kit's back on the counter. Buckles counted. Good. You can have your own clothes again.",
      "You smell like you took my kit somewhere I wouldn't. Good. That's what it's for.",
      "Back alive, with my gear. You're my favourite sort of borrower.",
      "Sign it back in. Here. And here. And there's a spot of blood on page nine. Yours?",
    ],
    onDeath: [
      "Kit came home this morning. Folded on the counter. Damp. They always come home damp.",
      "The kit's back. You're back. Your own things are back. Only the finds are gone. Could be worse.",
      "Died in my kit, did you? Kit's fine. I'll brush the dream off it. You, I can't help.",
      "Your kit's candle went out at half past something. I noted the time. I always note the time.",
    ],
    depthLines: [
      { minFloor: 10, lines: ["Past floor ten. Stop borrowing Undercroft kits, you'll embarrass them."] },
      { minFloor: 30, lines: ["Thirty. Now you'll want to go back up for tallow. Everybody does. That's my living."] },
      { minFloor: 50, lines: ["Fifty. I've kits for every depth you've already been. You'll need them. You'll see."] },
      { minFloor: 70, lines: ["Seventy. Lent a kit to someone who went that deep once. Kit came home. She didn't."] },
      { minFloor: 100, lines: ["The bottom. There's no kit for that. There's never been a kit for that. Sit a minute."] },
    ],
    secretHints: [
      "Borrow enough kits and I'll let you read the ledger. Some of the names are older than the ink.",
      "An Oddny Quell borrowed an Archive kit once. Returned it wet. That was longer ago than me.",
      "Weigh yourself on the grain scale in your smalls some time. Humour me.",
    ],
  },

  the_chandler: {
    name: "The Chandler",
    title: "Keeper of the Chandlery, Candle Order",
    shop: "chandlery",
    greeting: [
      "Softly, please. They're all listening, in their way.",
      "Your candle's on the fourth shelf. It's burning well. Don't look so surprised.",
      "Welcome to the Chandlery. Everyone who goes down is here. Mind the drips.",
      "A light for each who goes down. You're one of the lights.",
    ],
    idle: [
      "I gave up my name when I took these gloves. It's in a drawer. I visit it.",
      "The tall candles are careful. The short ones are brave. The guttering ones are both.",
      "When a candle goes out on its own, only I may pinch it. I'm very good at it. I hate it.",
      "The stubs of the dead go into the new candles. So nobody goes down entirely alone.",
      "The Long Candle has burned since the ledger began. It has never got shorter. I measure.",
      "Two candles on my desk. One lit, one not. I haven't decided which one is me.",
      "There was a second rule over the door. Scratched out before I was born. I've a guess.",
      "Keep the light low, let it sleep. It knelt because it was tired. That's the official view.",
    ],
    onReturn: [
      "Your candle leaned a little tonight. Towards the pit. It's straight again now. Welcome home.",
      "You're back, and your flame never flickered. Well. Once. Around the fourth hour.",
      "No questions till morning. I'll just sit here with the candles. Being glad.",
      "I watched your candle the whole time. That's not true. I watched most of it.",
    ],
    onDeath: [
      "Your candle went out. I pinched the wick myself, and said your name. It's what we do.",
      "Your old stub went into your new candle. You light your own way now. Like Bowe did. Don't think about it.",
      "It guttered at the ninth hour. The flame leaned down before it went. They always lean down.",
      "Here's a new candle. Same name. Slightly shorter. That's how it goes.",
    ],
    depthLines: [
      { minFloor: 5, lines: ["Five breaths. The Well knows your taste now. It'll let you up. It's polite, in its way."] },
      { minFloor: 10, lines: ["You've met Hollis. He sealed them in, you know. Out of love. It's always love, down there."] },
      { minFloor: 30, lines: ["You've been in the Choir. Did it ask you anything? No? Good. Don't answer if it does."] },
      { minFloor: 50, lines: ["Fifty. Your candle has started to lean when you're down. Only slightly. Only towards it."] },
      { minFloor: 70, lines: ["Seventy. The Wakers will want a word. So will we. Listen to both and trust neither."] },
      { minFloor: 90, lines: ["You've been in the dark. Your candle nearly went out and then didn't. Something found you."] },
      { minFloor: 100, lines: ["You've seen its face. It's on yours. Whatever you answered, I'll keep your candle lit."] },
    ],
    secretHints: [
      "The drawing of the Giant on the back wall is older than the Order. Look at its hand. Then look at his.",
      "If you find something iron and bell-shaped down there, bring it to me. Please. Not to the tower.",
      "The Long Candle is on the top shelf. Go deep enough and I'll let you look at it properly.",
    ],
  },

  tibb: {
    name: "Tibb",
    title: "Who Counts",
    greeting: [
      "You're three hundred and twelve. Delvers, I mean. Since I started counting.",
      "Hello. You took forty-one steps from the portal. Last time it was forty. Did you grow?",
      "One, two, three. That's you, me and the Giant. He counts. He's just slow.",
      "I'm counting candles. Don't stand there, you're blocking eleven.",
    ],
    idle: [
      "Thirty-one stalls. Mam says there were forty. I counted. Thirty-one.",
      "Eleven went down today and thirteen came up. I counted twice. Nobody believes me.",
      "Do you want to hear the rhyme? One is a candle and one is a spade...",
      "The Giant's heart goes once every twenty seconds. I timed it with mine. Mine's faster. I'm small.",
      "You can't ask a delver anything till morning. So I count them instead. Counting isn't asking.",
      "There are more candles than people in Kneel. I checked. Twice.",
      "Out goes you. That's the end. Then whoever's out runs to the fog and back.",
    ],
    onReturn: [
      "You came back up! That's eleven down and twelve up today. See? It never matches.",
      "I counted you going down and now I've counted you coming up. That's the good kind.",
      "No questions till morning. I'm not asking. I'm just counting your bags.",
      "Welcome back. You've got nine new scratches. I'm not asking. I'm counting.",
    ],
    onDeath: [
      "I counted you going down and not coming up. Then you came up anyway. That's not how counting works.",
      "Your candle went out. I counted to a hundred and it was still out. Then there was a new one.",
      "The Wall's got a new name on it. I can read it. It's yours.",
      "Mam says don't count the dead. I don't. I count the ones who come back after.",
    ],
    depthLines: [
      { minFloor: 10, lines: ["One is a candle and one is a spade. You've done One. Nine more. Or ten. Depends how you count."] },
      { minFloor: 30, lines: ["You've been to Three. Did the song have anybody in it? The rhyme says it doesn't."] },
      { minFloor: 50, lines: ["Five is a honeycomb, sticky and sweet. Did you lick it? I would."] },
      { minFloor: 80, lines: ["Eight is a clock that is turning the place. Was it turning? Was it turning you?"] },
      { minFloor: 91, lines: ["You've been to Ten. Come here. There's more rhyme. Nobody else knows it. Come here."] },
      { minFloor: 100, lines: ["I count everyone's answer. I'll tell you how many said the same as you. If you want."] },
    ],
    secretHints: [
      "I know two more lines. I'll only sing them to someone who's been all the way to Ten.",
      "Stand on the Giant's thumb at night and count. You'll get to twenty and then you'll feel it.",
      "The fog always brings you back to the market. Unless you carry tallow. Then it goes somewhere first.",
    ],
  },

  dunny_rook: {
    name: "Dunstan \"Dunny\" Rook",
    title: "Ex-Delver, Floor 34",
    greeting: [
      "Sit down, sit down. You're buying. That's not a question. No questions before morning.",
      "Another one. Look at you. All your fingers. Enjoy them.",
      "Dunny Rook. Floor thirty-four. Seven fingers. Ask me how. No, don't. I'll tell you anyway.",
      "The Well? A pint a floor. Thirty-four pints. Discount for friends.",
    ],
    idle: [
      "Attempt number four thousand one hundred and twelve. Looked at me like it wanted marking.",
      "Three of my fingers are in a Reliquary on floor twenty-three. Bring them up. I'd like them burned.",
      "Kneel low. And rise after. And have a drink after that. That's the bit they leave out.",
      "I'll go back down one day. Not today. Today's not a going-down day. Neither was yesterday.",
      "My gran was a Rook. And hers. We've always been Rooks. I think. Rooks all the way down.",
      "There's a chair by the window nobody sits in. I don't. You don't. Nobody does.",
      "The Foundry hammers go one-two-three, one-two-three. I still hear it. I hear it in the rain.",
    ],
    onReturn: [
      "You're back! The Stump owes you bread and salt. I owe you nothing. But I'll drink to you.",
      "Came up, did you? That's the trick. Going down's just falling slowly.",
      "Look at you. Heavier. Richer. Sadder? A bit. It suits everybody, eventually.",
      "Sit. I won't ask. It's the law. But if you want to tell me anything, I've ears. Most of them.",
    ],
    onDeath: [
      "Died, eh? First one's the worst. Second's the second worst. After that it's a sort of hobby.",
      "The Well's got your gear. It's got my fingers. We should start a club.",
      "Your name's on the Wall. I'll drink to it. I drink to all of them. It's a lot of drinking.",
      "Dying's not the end, down there. It's just very, very rude.",
    ],
    depthLines: [
      { minFloor: 20, lines: ["Twenty? I did twenty. That's where the water gets in your boots and never gets out."] },
      { minFloor: 34, lines: ["Thirty-four. That's me. That's my number. You've caught me up. Stop there. Please."] },
      { minFloor: 40, lines: ["Past me, then. Go on. Go on and tell me what's after. No — morning."] },
      { minFloor: 70, lines: ["Seventy. You didn't see a Rook down there? A Tamsin Rook? No. Course not. Why would you."] },
      { minFloor: 100, lines: ["You went to the bottom. I'd buy you a drink but I'd have to stand up."] },
    ],
    secretHints: [
      "The chair by the window. Merrow pours two cups for it some nights. Only for folk who've died a few times.",
      "Gran used to say set a fire on the Ash Step at night and the smoke goes the wrong way. Gran drank.",
      "There's a door on Tanner's Row with no handle. Opens for folk who died on thirteen. So I'm told.",
    ],
  },

  absalom_quell: {
    name: "Absalom Quell",
    title: "Keeper of the Little Well",
    greeting: [
      "Evening. Or it will be. The Little Well talks better in the evening.",
      "Mind the rope. It's older than the well. Don't ask how.",
      "Water's free. The listening costs you a minute's quiet.",
      "Absalom Quell. I keep the well. Mostly it keeps me.",
    ],
    idle: [
      "Forty-one years I've written down what it whispers. Mostly last words. Some of it's questions.",
      "It said 'is it heavy?' last Tuesday. Twice. I wrote it down twice.",
      "The Keepers dropped something down here once. Something iron. The well swallowed it.",
      "Great-aunt Wenna rang the bell one night. Then she wasn't anywhere. Her candle's still lit.",
      "There are Quells in the Archive. Old ones. Older than ink. I don't like to think about it.",
      "The water's sweet. Always sweet. Even the year the fog came into the lane.",
      "If you hear your own name down there, don't answer. That's not mystery. That's advice.",
    ],
    onReturn: [
      "You're up. The well said you would be. It says a lot of things. That one was right.",
      "Have a drink. It's only water. It's only ever water. Mostly.",
      "Welcome back. The well's quiet tonight. That's you, I expect. Nothing to say about you.",
    ],
    onDeath: [
      "The well said your last words last night. I wrote them down. You can read them. You might not want to.",
      "I heard you, you know. Down the well. Just a word. I won't say which.",
      "Another line in the ledger. Yours. I spelled your name right. I always spell them right.",
    ],
    depthLines: [
      { minFloor: 20, lines: ["The Archive. Did you see any Quells? Don't tell me. Your face will. Oh. Oh, you did."] },
      { minFloor: 60, lines: ["Sixty. The well's started saying your name at night. Now and then. Fondly, I think."] },
      { minFloor: 100, lines: ["The well hasn't whispered since you came up. First time in forty-one years."] },
    ],
    secretHints: [
      "Come at night. Put your ear to the stones. You'll hear who went last. That's all. That's enough.",
      "Great-aunt Wenna said lightning would ring the old bell. She was right. She was also gone by morning.",
      "The Keepers' iron thing went down this well. I hear it clanking about in the Archive, in my dreams.",
    ],
  },
};
