import type { StratumText } from "./types";

/** Per-stratum text: arrival lines, descriptions, resource blurbs. */
export const STRATA_TEXT: StratumText[] = [
  {
    index: 0,
    name: "The Undercroft",
    epithet: "Where the first villagers buried themselves closer to God.",
    village: "Bowe",
    question: "Where did you think you were going?",
    arrival: [
      "Every flame here leans the same way. Down.",
      "Somewhere below you, a shovel. Chk. Chk.",
      "The candles are fresh. Somebody is keeping them.",
      "Bone dust. It gets in your teeth and stays.",
      "A painted skull watches you arrive. Its name, apparently, is Agnes.",
      "The air is moving downhill, like it has an appointment.",
      "It smells of mutton fat and wet limestone and old, careful grief.",
      "Every bone in this place was counted once. You are not on the list.",
    ],
    description:
      "Low vaults of sweating limestone, ossuary walls stacked by kind — femurs with femurs, skulls with their names painted on — and candles everywhere, rendered from the dead so they could light their own way down. The village of Bowe went down this stair together, singing. The dream remembers them still going.",
    resourceBlurbs: {
      grave_tallow:
        "Rendered in Bowe's vats from the dead, to see by. It remembers being somebody; enchantments stick to it the way names do.",
      ossuary_bone: "Counted, labelled, shelved. Bone keeps count — every upgrade is a mark on one.",
    },
    warden: { id: "sexton", name: "Hollis Crane, the Sexton of Bowe" },
  },
  {
    index: 1,
    name: "The Drowned Archive",
    epithet: "Where scholars tried to write God's true name, and the water rose.",
    village: "Stoop",
    question: "What is my name?",
    arrival: [
      "The water is exactly as deep as it was yesterday. Nobody here believes that.",
      "Somewhere, pages are turning with nobody to turn them.",
      "A brass bell for closing time. It has been ringing for a very long time.",
      "QUIET PLEASE, says a sign, and the whole floor obliges.",
      "Wet paper, iron ink, cold stone. The smell of homework.",
      "Something under the water is reading by lamplight.",
      "Drying pages hang from the balconies like laundry nobody will fetch.",
      "Your footsteps are the loudest thing here. Something has noticed.",
    ],
    description:
      "Flooded reading rooms and galleries half under black water, rolling ladders and balconies strung with drying pages. Stoop gave every child a desk and a portion of God's true name to copy, and kept writing as the water came up an inch a year. The ink ran. They are still at their desks.",
    resourceBlurbs: {
      drowned_vellum: "The only paper that doesn't mind being wet. It has been wet for a thousand years. Reforging writes on it.",
      ink_sac: "Cuttle ink, still trying to spell something. Drowned ink writes every scroll.",
    },
    warden: { id: "oddny_quell", name: "Magister Oddny Quell, Keeper of the Last Line" },
  },
  {
    index: 2,
    name: "The Mycelial Choir",
    epithet: "Where a people sang together until there was only one voice.",
    village: "Lean",
    question: "Which of you is speaking?",
    arrival: [
      "A chord, held. It shifts key when it notices you.",
      "The walls breathe. Slowly. In time with something.",
      "Wet bread, turned earth, and — faintly — somebody's hair.",
      "Blue light from the gills of mushrooms taller than houses.",
      "The spores catch your lantern like dust in a church.",
      "Everything here is soft. Your footsteps are the only hard thing.",
      "Somewhere a single voice is singing slightly out of tune, and hating it.",
      "The song is very happy to see you. That is the problem.",
    ],
    description:
      "Caverns of glowing caps and breathing walls, thick with spores and filled with one enormous, contented song. The people of Lean believed God was hard of hearing, so they sang together, then breathed together, then grew together, until they were one voice loud enough to carry — with nothing left to say but us.",
    resourceBlurbs: {
      choir_spore: "A pinch of the chord. It makes things agree with each other — two enchantments, one harmony.",
      lumen_cap: "The blue cap Lean ate to see each other in the dark. Every good draught below twenty has some in it.",
    },
    warden: { id: "ysolde_half_sung", name: "Sister Ysolde Sallow, Half-Sung" },
  },
  {
    index: 3,
    name: "The Cinder Foundry",
    epithet: "Where smiths tried to forge a god they could hold.",
    village: "Raise",
    question: "Is it heavy?",
    arrival: [
      "The hammers are keeping time. Three-four. A waltz for anvils.",
      "Heat on your face like an open oven door.",
      "Sulphur, hot iron, and a faint smell of your own eyebrows.",
      "A conveyor carries nothing, patiently, to nowhere.",
      "Somewhere a stamp comes down. REJECT.",
      "Coal dust on everything, including the air.",
      "Numbered faces on the walls, all looking slightly disappointed.",
      "The rock here is warm. Nobody in Raise ever asked why.",
    ],
    description:
      "Forges, lava troughs, cranes and conveyors, all of it still running. Raise melted its rings and cradle-rails to make a god small enough to carry, and judged every attempt, and rejected every one. The rejects still walk to be judged again. The slag heap is bigger than the town was.",
    resourceBlurbs: {
      slag_iron: "Rejected gods, melted. Every ingot has a chip on its shoulder about it. Heavy upgrades need heavy iron.",
      ember_core: "A stone that stays warm for years. It's warm because something enormous is asleep nearby.",
    },
    warden: { id: "last_attempt", name: "The Last Attempt (Idony Fenwright, its heart)" },
  },
  {
    index: 4,
    name: "The Gilded Hive",
    epithet: "Where worshippers served a Queen who never asked for anything.",
    village: "Bend",
    question: "What do you want?",
    arrival: [
      "Gold light through amber, like walking into a memory.",
      "The hum is in your teeth before it's in your ears.",
      "The floor is tacky. Your boots make small kissing noises.",
      "Wax, pollen, warm bread, and something sweet that has gone slightly over.",
      "A petition box, full to the lid. All the petitions are the same.",
      "Everyone here is busy. Nobody here is in a hurry.",
      "Honey sheets down the walls, patient as a clock.",
      "It is warm, and golden, and nobody has asked you for anything. Yet.",
    ],
    description:
      "A cathedral of hexagons and amber windows, humming. Bend looked for the one person who asked for nothing and made her Queen, and fed her the best of everything, and served, and served. The dream remembers them more bee than person. They never once asked her what she wanted.",
    resourceBlurbs: {
      royal_wax: "Sealed by a thousand careful mouths. Seals one enchantment so a reforge can't touch it — or smear it on and pass for family.",
      amber: "Sap and honey gone to stone with things inside. It keeps what it holds, including upgrades.",
    },
    warden: { id: "maud_ellery", name: "Maud Ellery, the Queen Who Never Asked" },
  },
  {
    index: 5,
    name: "The Frozen Liturgy",
    epithet: "Where a Mass swore never to end, and time froze to keep the promise.",
    village: "Fold",
    question: "Are you finished?",
    arrival: [
      "One organ note, held. You stop hearing it after a while. Then you don't.",
      "Snowflakes hang in the air. You could walk around one.",
      "Your breath is the only thing here that moves.",
      "The candle flames are solid. They give off cold.",
      "No rot. Nothing rots where nothing happens.",
      "A congregation, kneeling. Every one of them mid-word.",
      "Incense smoke, frozen into coral.",
      "Somewhere, a man has been holding a cup over his head for a very long time.",
    ],
    description:
      "Nave after blue-white nave of a Mass that never stopped. Fold kept its prayer going for four hundred years in shifts, and when the winter came and the singers thinned, they prayed that the hour would not end until the prayer was done. It didn't. Warm anything here and its hour starts again.",
    resourceBlurbs: {
      rime_crystal: "Frost that formed on the vow itself. It holds a moment still so the next can come sooner.",
      stilled_breath: "A breath someone started and never finished, corked. The vial fogs from the inside.",
    },
    warden: { id: "aurel_vane", name: "Celebrant Aurel Vane, Who Keeps the Hour" },
  },
  {
    index: 6,
    name: "The Red Garden",
    epithet: "Where gardeners grew a body worthy of God, and nobody came to wear it.",
    village: "Offer",
    question: "Is this what I look like?",
    arrival: [
      "Warm and close, like the inside of a mitten.",
      "The walls have a pulse. It's slower than yours.",
      "Cut grass and iron. Someone has been gardening.",
      "Every plant here is labelled, with thanks.",
      "The fruit looks like kidneys. It smells lovely. Don't.",
      "A heartbeat under the floor, too slow, like a sleeper's.",
      "A sun hat on a bench. There is no sun.",
      "Everything here was a gift once.",
    ],
    description:
      "Beds and trellises, bone fences and red vines, acid pools where the garden digests. Offer thought God had left because nothing in the world was fit for it to live in, so each of them gave a piece of themselves and planted it, and grew a body. It was enormous, and beautiful, and empty. The garden kept growing.",
    resourceBlurbs: {
      ichor: "The Garden's sap, clear gold with a thread of red. It closes wounds and doesn't ask whose.",
      heartseed: "Grown from a sliver of someone's heart. Beats once a minute. Plant it in an item and the item grows with you.",
    },
    warden: { id: "the_vessel", name: "The Vessel, worn by Tamsin Rook" },
  },
  {
    index: 7,
    name: "The Orrery",
    epithet: "Where engineers built a machine to turn the dreamer in its sleep. It still turns.",
    village: "Reach",
    question: "Where are you taking me?",
    arrival: [
      "Ticking, at every size, from your ear to the floor.",
      "The room is turning. Slowly. On purpose.",
      "Brass, oil, chalk dust, ozone.",
      "Painted stars on the ceiling. They were somewhere else a moment ago.",
      "Something vast ticks once a minute and the dust comes down.",
      "Everything here is on schedule except you.",
      "A pendulum the size of a house goes past, politely.",
      "Someone here knew exactly what they were doing. That was the problem.",
    ],
    description:
      "Rotating rooms, gear-tooth bridges, pendulums sweeping through halls. Reach knew God was asleep and thought it kinder to steer than to wake, so they built a machine around the dream to turn it toward gentler winters. Every correction needed another. The machine turns them too.",
    resourceBlurbs: {
      orichalcum_gear: "A gear cut to the period of one particular star. Things fitted with it come round sooner.",
      mainspring: "A coil of stored turning. It wants to let go, and it will, once more than you expected.",
    },
    warden: { id: "ione_castellan", name: "Horologer Ione Castellan, the Brake" },
  },
  {
    index: 8,
    name: "The Unlit",
    epithet: "Where a people put out every light so God would have to come looking.",
    village: "Turn",
    question: "Where are you?",
    arrival: [
      "Dark. Yours is the only light, and everything knows it.",
      "Somewhere, a voice is counting. Ninety-seven. Ninety-eight.",
      "Your lantern comes back from a hundred mirrors. Not all of it.",
      "Snuffed wicks. Cold stone that has never been warm.",
      "Hundreds of mirrors, turned to face the wall. One isn't.",
      "It is very quiet. Somebody is being very quiet.",
      "A cold draft. Something enormous turning its head.",
      "Ready or not.",
    ],
    description:
      "Halls of mirrors in total dark. Turn hid from God the way children hide from a parent — put out every lamp, blinded the windows, waited, counting, to be found. They hid too well. Something has been looking for them ever since, and it is drawn to light.",
    resourceBlurbs: {
      umbral_glass: "Mirror silvered with the dark. You look in it and it looks away.",
      echo: "A sound that never finished bouncing, caught in a stoppered horn. Things made with it happen twice.",
    },
    warden: { id: "olly_ferrow", name: "Olly Ferrow, Who Hid Best" },
  },
  {
    index: 9,
    name: "The Threshold",
    epithet: "Inside the dreamer. It dreams of Kneel, remembered wrong.",
    village: "Stand",
    question: "(withheld)",
    arrival: [
      "Home. Almost.",
      "The Market Ring has forty stalls. It hasn't had forty stalls in years.",
      "The fog is inside the houses, pressed against the glass.",
      "Everyone is standing at the rim, looking down.",
      "Mother Sallow's shop. Old Hask's eye. The wrong way round.",
      "No Giant. Just the rim, and a very long way down, and something pale.",
      "It smells of every place you've been, faintly, like a house after supper.",
      "Somebody has been expecting you. Everybody has.",
    ],
    description:
      "The dreamer's own mind, where the dream is thinnest. It remembers the last thing it saw before it slept — a village at the rim, everyone standing — and fills it with whatever village is there now. So: Kneel. Wrong. At the bottom of the pit, the Head, eyes closed.",
    resourceBlurbs: {
      godtear: "A tear the dreamer cried in its sleep. The dream keeps what it touches; this is what it touched.",
    },
    warden: { id: "anneth_of_stand", name: "Anneth of Stand, the First Asker" },
  },
];
