import { Registry } from "../registry";
import type { SpellDef } from "../types";
import { Surface } from "../types";

/** Spells: player focus/relic abilities and creature spell attacks share one
 * table. A spell is pure data — delivery + effects; shared/sim/spells.ts
 * executes any of them, and amplifiers rewrite the delivery. */
export const SPELLS = new Registry<SpellDef>("spell");

SPELLS.register(
  // ── Focus primaries ─────────────────────────────────────────────────────
  {
    id: "bolt",
    name: "Arcane Bolt",
    desc: "A quick bolt of raw arcana.",
    element: "arcane",
    mana: 3,
    cooldown: 0.28,
    noise: 6,
    delivery: {
      kind: "projectile",
      speed: 34,
      radius: 0.1,
      gravity: 0,
      lifetime: 1.6,
      onHit: [
        { type: "damage", amount: 14, element: "arcane" },
        { type: "impulse", strength: 2.5 },
      ],
    },
    vfx: { color: "#8fd8ff", trail: "arcane", light: { color: "#7fc8ff", intensity: 2.5, radius: 5 } },
    sfx: { cast: "cast_arcane", hit: "hit_arcane" },
  },
  {
    id: "ember_scatter",
    name: "Ember Scatter",
    desc: "A fistful of embers that arc and ignite what they touch.",
    element: "fire",
    mana: 7,
    cooldown: 0.6,
    noise: 8,
    delivery: {
      kind: "projectile",
      speed: 24,
      radius: 0.08,
      gravity: 0.4,
      lifetime: 1.4,
      count: 5,
      spread: 9,
      onHit: [
        { type: "damage", amount: 6, element: "fire" },
        { type: "status", status: "burning", duration: 2, chance: 0.35 },
      ],
    },
    vfx: { color: "#ff9a3a", trail: "ember", light: { color: "#ff8a2a", intensity: 1.2, radius: 3.5 } },
    sfx: { cast: "cast_fire", hit: "hit_fire" },
  },
  {
    id: "frost_shard",
    name: "Frost Shard",
    desc: "A splinter of the Liturgy's cold. Chills; freezes the wet; turns water to ice.",
    element: "frost",
    mana: 5,
    cooldown: 0.42,
    noise: 5,
    delivery: {
      kind: "projectile",
      speed: 30,
      radius: 0.1,
      gravity: 0.05,
      lifetime: 1.5,
      onHit: [
        { type: "damage", amount: 12, element: "frost" },
        { type: "status", status: "chilled", duration: 3 },
        { type: "surface", surface: Surface.Ice, radius: 0.8 },
      ],
    },
    vfx: { color: "#bfefff", trail: "frost", light: { color: "#9fe0ff", intensity: 1.8, radius: 4 } },
    sfx: { cast: "cast_frost", hit: "hit_frost" },
  },
  {
    id: "spark",
    name: "Spark",
    desc: "Crackling storm-light. Chains between bodies — and through water.",
    element: "storm",
    mana: 4,
    cooldown: 0.3,
    noise: 7,
    delivery: {
      kind: "projectile",
      speed: 44,
      radius: 0.07,
      gravity: 0,
      lifetime: 1,
      onHit: [
        { type: "damage", amount: 10, element: "storm" },
        { type: "chain", count: 2, range: 5, damage: 6, element: "storm" },
        { type: "status", status: "shocked", duration: 0.8, chance: 0.5 },
      ],
    },
    vfx: { color: "#f4f7a0", trail: "spark", light: { color: "#e8f07a", intensity: 2.2, radius: 4.5 } },
    sfx: { cast: "cast_storm", hit: "hit_storm" },
  },
  {
    id: "void_lance",
    name: "Void Lance",
    desc: "A slow, heavy spear of nothing. Pierces, and the hole it leaves pulls.",
    element: "void",
    mana: 10,
    cooldown: 0.85,
    noise: 9,
    delivery: {
      kind: "projectile",
      speed: 22,
      radius: 0.16,
      gravity: 0,
      lifetime: 2,
      pierce: 2,
      onHit: [
        { type: "damage", amount: 30, element: "void" },
        { type: "impulse", strength: 6 },
      ],
    },
    vfx: { color: "#b27cff", trail: "void", light: { color: "#9a5cff", intensity: 3, radius: 6 } },
    sfx: { cast: "cast_void", hit: "hit_void" },
  },
  {
    id: "venom_glob",
    name: "Venom Glob",
    desc: "A lobbed sac of acid that bursts into a corroding pool.",
    element: "venom",
    mana: 8,
    cooldown: 0.8,
    noise: 5,
    delivery: {
      kind: "projectile",
      speed: 16,
      radius: 0.18,
      gravity: 1,
      lifetime: 3,
      onHit: [
        { type: "damage", amount: 10, element: "venom" },
        { type: "surface", surface: Surface.Acid, radius: 1.6 },
        { type: "status", status: "poisoned", duration: 5 },
      ],
    },
    vfx: { color: "#8cff5a", trail: "venom", light: { color: "#6cff3a", intensity: 1.5, radius: 3.5 } },
    sfx: { cast: "cast_venom", hit: "splash" },
  },
  // ── Focus secondaries ───────────────────────────────────────────────────
  {
    id: "force_blast",
    name: "Force Blast",
    desc: "A concussive orb. Shoves everything — including you, if you aim at your feet.",
    element: "force",
    mana: 12,
    cooldown: 1.1,
    noise: 14,
    delivery: {
      kind: "projectile",
      speed: 22,
      radius: 0.2,
      gravity: 0.15,
      lifetime: 1.2,
      detonateOnExpire: true,
      onHit: [{ type: "explode", radius: 3.2, damage: 18, element: "force", impulse: 26, friendlyFactor: 0.25 }],
    },
    vfx: { color: "#e6d9ff", trail: "force", light: { color: "#d8c8ff", intensity: 3, radius: 6 } },
    sfx: { cast: "cast_force", hit: "explosion_medium" },
  },
  {
    id: "fireball",
    name: "Fireball",
    desc: "The classic. Bursts into flame and sets the floor burning where oil or webs wait.",
    element: "fire",
    mana: 14,
    cooldown: 1.2,
    noise: 14,
    delivery: {
      kind: "projectile",
      speed: 20,
      radius: 0.22,
      gravity: 0.25,
      lifetime: 2,
      detonateOnExpire: true,
      onHit: [
        { type: "explode", radius: 3, damage: 24, element: "fire", impulse: 12 },
        { type: "surface", surface: Surface.Fire, radius: 1.4 },
        { type: "status", status: "burning", duration: 4, chance: 0.8 },
      ],
    },
    vfx: { color: "#ff7a2a", trail: "fire", light: { color: "#ff6a1a", intensity: 4, radius: 7 } },
    sfx: { cast: "cast_fire", hit: "explosion_medium" },
  },
  {
    id: "frost_nova",
    name: "Frost Nova",
    desc: "A ring of cold around you. Water becomes ice; the wet become statues.",
    element: "frost",
    mana: 16,
    cooldown: 3,
    noise: 10,
    delivery: {
      kind: "nova",
      radius: 4.5,
      onHit: [
        { type: "damage", amount: 12, element: "frost" },
        { type: "status", status: "chilled", duration: 4 },
        { type: "impulse", strength: 5, up: 1 },
        { type: "surface", surface: Surface.Ice, radius: 4 },
      ],
    },
    vfx: { color: "#bfefff", light: { color: "#9fe0ff", intensity: 5, radius: 8 } },
    sfx: { cast: "freeze" },
  },
  {
    id: "chain_lightning",
    name: "Chain Lightning",
    desc: "A beam of storm that leaps from body to body.",
    element: "storm",
    mana: 14,
    cooldown: 0,
    channeled: true,
    noise: 12,
    delivery: {
      kind: "beam",
      range: 14,
      width: 0.15,
      tick: 0.15,
      onHit: [
        { type: "damage", amount: 5, element: "storm" },
        { type: "chain", count: 3, range: 5, damage: 3, element: "storm" },
        { type: "status", status: "shocked", duration: 0.5 },
      ],
    },
    vfx: { color: "#f4f7a0", light: { color: "#e8f07a", intensity: 3, radius: 6 } },
    sfx: { cast: "beam_loop" },
  },
  {
    id: "singularity",
    name: "Singularity",
    desc: "A seed of void that swells into a pulling dark, then collapses.",
    element: "void",
    mana: 22,
    cooldown: 4,
    noise: 12,
    delivery: {
      kind: "projectile",
      speed: 12,
      radius: 0.25,
      gravity: 0,
      lifetime: 0.9,
      detonateOnExpire: true,
      onHit: [
        { type: "pull", radius: 7, strength: 30, duration: 2.2 },
        { type: "explode", radius: 3, damage: 30, element: "void", impulse: 10 },
      ],
    },
    vfx: { color: "#7a3cff", trail: "void", light: { color: "#7a3cff", intensity: 4, radius: 8 } },
    sfx: { cast: "cast_void", hit: "black_hole_loop" },
  },
  // ── Relic abilities (Shift) ─────────────────────────────────────────────
  {
    id: "blink",
    name: "Blink",
    desc: "Step through the dream a few metres in the direction you move.",
    element: "arcane",
    mana: 10,
    cooldown: 1.4,
    noise: 3,
    delivery: { kind: "dash", distance: 6, duration: 0.14 },
    vfx: { color: "#d8c8ff" },
    sfx: { cast: "dash" },
  },
  {
    id: "grasp",
    name: "Grasp",
    desc: "Telekinesis. Hold Shift to lift a prop or small creature; release to throw it.",
    element: "force",
    mana: 6,
    cooldown: 0.5,
    noise: 2,
    delivery: { kind: "grasp", range: 9, maxMass: 60, throwSpeed: 24 },
    vfx: { color: "#bfa8ff", light: { color: "#a88cff", intensity: 1.5, radius: 3 } },
  },
  {
    id: "ward",
    name: "Ward",
    desc: "A brief shell of force that turns aside blows and shoves attackers back.",
    element: "force",
    mana: 18,
    cooldown: 6,
    noise: 6,
    delivery: {
      kind: "self",
      effects: [
        { type: "status", status: "blessed", duration: 2 },
        { type: "explode", radius: 2.5, damage: 0, element: "force", impulse: 18, friendlyFactor: 0 },
      ],
    },
    vfx: { color: "#e6d9ff", light: { color: "#d8c8ff", intensity: 3, radius: 5 } },
    sfx: { cast: "block" },
  },
  // ── Creature spells ─────────────────────────────────────────────────────
  {
    id: "wight_flame",
    name: "Candle Flame",
    desc: "A wight flicks its candle's flame.",
    element: "fire",
    mana: 0,
    cooldown: 0,
    noise: 4,
    delivery: {
      kind: "projectile",
      speed: 14,
      radius: 0.12,
      gravity: 0.1,
      lifetime: 2.2,
      onHit: [
        { type: "damage", amount: 9, element: "fire" },
        { type: "status", status: "burning", duration: 3, chance: 0.5 },
      ],
    },
    vfx: { color: "#ffb35a", trail: "ember", light: { color: "#ff9a3a", intensity: 2, radius: 4 } },
    sfx: { cast: "cast_fire", hit: "hit_fire" },
  },
  {
    id: "bone_shard",
    name: "Bone Shard",
    desc: "A sharpened finger bone, flung.",
    element: "physical",
    mana: 0,
    cooldown: 0,
    noise: 3,
    delivery: {
      kind: "projectile",
      speed: 26,
      radius: 0.07,
      gravity: 0.35,
      lifetime: 2,
      onHit: [
        { type: "damage", amount: 8, element: "physical" },
        { type: "status", status: "bleeding", duration: 3, chance: 0.3 },
      ],
    },
    vfx: { color: "#e8dcc0" },
    sfx: { cast: "dart_fire", hit: "hit_bone" },
  },
  {
    id: "trap_dart",
    name: "Dart",
    desc: "A trap's poisoned dart.",
    element: "physical",
    mana: 0,
    cooldown: 0,
    noise: 2,
    delivery: {
      kind: "projectile",
      speed: 38,
      radius: 0.05,
      gravity: 0.05,
      lifetime: 1.5,
      onHit: [
        { type: "damage", amount: 10, element: "physical" },
        { type: "status", status: "poisoned", duration: 4, chance: 0.6 },
      ],
    },
    vfx: { color: "#b0a080" },
    sfx: { hit: "hit_flesh" },
  },
  // ── Throwables ──────────────────────────────────────────────────────────
  {
    id: "thrown_oil_flask",
    name: "Oil Flask",
    desc: "Shatters into a slick of lamp oil.",
    element: "physical",
    mana: 0,
    cooldown: 0.6,
    noise: 5,
    delivery: {
      kind: "projectile",
      speed: 14,
      radius: 0.12,
      gravity: 1,
      lifetime: 4,
      onHit: [{ type: "surface", surface: Surface.Oil, radius: 2.2 }],
    },
    vfx: { color: "#6a5230" },
    sfx: { hit: "glass_shatter" },
  },
  {
    id: "thrown_fire_flask",
    name: "Fire Flask",
    desc: "Shatters into flame.",
    element: "fire",
    mana: 0,
    cooldown: 0.6,
    noise: 8,
    delivery: {
      kind: "projectile",
      speed: 14,
      radius: 0.12,
      gravity: 1,
      lifetime: 4,
      onHit: [
        { type: "explode", radius: 2, damage: 16, element: "fire", impulse: 6 },
        { type: "surface", surface: Surface.Fire, radius: 2 },
      ],
    },
    vfx: { color: "#ff7a2a", light: { color: "#ff6a1a", intensity: 1.5, radius: 3 } },
    sfx: { hit: "glass_shatter" },
  },
);
