import type { CreatureDef } from "../types";
import { Surface } from "../types";

/** Stratum 1 — the Undercroft. (Expanded by the bestiary pass.) */
export const UNDERCROFT_CREATURES: CreatureDef[] = [
  {
    id: "grave_rat",
    name: "Grave Rat",
    desc: "Fat on the dead, bold in numbers, cowards alone.",
    faction: "vermin",
    radius: 0.22,
    height: 0.35,
    mass: 7,
    movement: "walk",
    stats: { hp: 14, speed: 4.2, runMult: 1.5, turnRate: 540 },
    senses: { sight: 10, fov: 200, hearing: 14, darkvision: true },
    intelligence: 0.15,
    temperament: { aggression: 0.7, courage: 0.4, callRadius: 8 },
    attacks: [{ id: "bite", kind: "lunge", range: 1.2, windup: 0.25, recover: 0.4, cooldown: 0.9, damage: 5, element: "physical", leapSpeed: 6, effects: [{ type: "status", status: "bleeding", duration: 2, chance: 0.25 }] }],
    behaviors: ["wander", "hunt", "flee", "feed", "swarm", "investigate", "avoid_hazard"],
    flammable: true,
    drops: { gold: 2, goldChance: 0.3, lootChance: 0.04, materials: [{ id: "grave_tallow", chance: 0.1 }] },
    model: "rat",
    voice: "rat",
  },
  {
    id: "ossuary_shambler",
    name: "Ossuary Shambler",
    desc: "Bones that remember the shape of a person, badly.",
    faction: "dead",
    radius: 0.34,
    height: 1.7,
    mass: 45,
    movement: "walk",
    stats: { hp: 60, armor: 2, speed: 2.2, runMult: 1.3, turnRate: 180, res: { venom: 1, fire: -0.25, force: -0.3 } },
    senses: { sight: 14, fov: 120, hearing: 12, darkvision: true },
    intelligence: 0.3,
    temperament: { aggression: 1, courage: 0 },
    attacks: [
      { id: "swipe", kind: "melee", range: 1.7, windup: 0.55, recover: 0.6, cooldown: 1.3, damage: 14, element: "physical", impulse: 6 },
      { id: "fling", kind: "ranged", range: 12, minRange: 4, windup: 0.7, recover: 0.8, cooldown: 3, damage: 0, element: "physical", spell: "bone_shard", weight: 0.5 },
    ],
    behaviors: ["patrol", "hunt", "investigate", "retaliate", "avoid_hazard"],
    immune: ["poisoned", "bleeding"],
    drops: { gold: 6, goldChance: 0.5, lootChance: 0.15, materials: [{ id: "ossuary_bone", chance: 0.4 }] },
    model: "shambler",
    voice: "bones",
  },
  {
    id: "candle_wight",
    name: "Candle Wight",
    desc: "A mourner who never stopped keeping vigil. The candle on its head is its heart.",
    faction: "dead",
    radius: 0.3,
    height: 1.6,
    mass: 30,
    movement: "walk",
    stats: { hp: 38, speed: 2.6, runMult: 1.2, turnRate: 220, res: { fire: 0.8, frost: -0.3 } },
    senses: { sight: 18, fov: 140, hearing: 10 },
    intelligence: 0.6,
    temperament: { aggression: 0.8, courage: 0.3 },
    attacks: [{ id: "flick", kind: "spell", range: 14, minRange: 3, windup: 0.6, recover: 0.5, cooldown: 1.8, damage: 0, element: "fire", spell: "wight_flame" }],
    behaviors: ["patrol", "kite", "flee", "tend", "investigate", "avoid_hazard"],
    light: { color: "#ffb35a", intensity: 1.8, radius: 6 },
    drops: { gold: 5, goldChance: 0.6, lootChance: 0.14, materials: [{ id: "grave_tallow", chance: 0.6 }] },
    model: "wight",
    voice: "wight",
  },
  {
    id: "sexton",
    name: "The Sexton",
    desc: "The first gravedigger of the rim. Still digging. Still burying anyone who stands still.",
    faction: "dead",
    radius: 0.7,
    height: 3.2,
    mass: 400,
    movement: "walk",
    stats: { hp: 900, armor: 4, speed: 2.4, runMult: 1.6, turnRate: 140, res: { venom: 1, force: 0.4 } },
    senses: { sight: 30, fov: 160, hearing: 30, darkvision: true },
    intelligence: 0.7,
    temperament: { aggression: 1, courage: 0 },
    attacks: [
      { id: "shovel_sweep", kind: "melee", range: 2.8, windup: 0.8, recover: 0.7, cooldown: 1.6, damage: 30, element: "physical", impulse: 22 },
      { id: "grave_slam", kind: "slam", range: 4, windup: 1.2, recover: 1, cooldown: 5, damage: 36, element: "force", impulse: 30, effects: [{ type: "surface", surface: Surface.Ash, radius: 3 }] },
      { id: "bone_volley", kind: "ranged", range: 20, minRange: 5, windup: 0.9, recover: 0.6, cooldown: 4, damage: 0, element: "physical", spell: "bone_shard", weight: 0.8 },
    ],
    behaviors: ["guard", "hunt"],
    immune: ["poisoned", "bleeding", "feared", "stunned"],
    drops: { gold: 120, goldChance: 1, lootChance: 1, materials: [{ id: "grave_tallow", chance: 1 }, { id: "ossuary_bone", chance: 1 }] },
    model: "sexton",
    voice: "giant",
    warden: { title: "Warden of the Undercroft", phases: 2 },
  },
];
